name: Build and Deploy Advent Calendar App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v3

      # Java und Maven installieren
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Abhängigkeiten installieren und JAR bauen
      - name: Build JAR file
        run: mvn clean package

      # JAR-Datei für GitHub Pages bereitstellen
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target
